<?php include 'templates/header.phtml' ?>

<div class="about">

    <div style="display: flex;width:100vw;height:50vh;background-color:rgb(44, 44, 44);align-items:center;justify-content:center;">
        <p style="font-family: 'Mohave'; color :white;font-size:30px">
            Buenas a todos! Somos dos amigos con un emprendimiento que queremos compartiles.
            <br> La idea de gonzalo fue hacer un local de hamburguesas en la localidad de Laprida.
            <br>Y este seria un concepto o boceto de la pagina q estamos desarrollando para el local.
            <br>Somos dos estudiantes de la TUDAI, Gonzalo mas volcado a la parte del backend y David
            <br> hacia la del frontend.
        </p>

    </div>

</div>

<?php include 'templates/footer.phtml' ?>