<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<? echo BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="./src/burguer.png">
    <link rel="stylesheet" type="text/css" href="src/style.css">
    <title>Bamba's Burguer</title>
</head>

<body>

    <section class="menu" style="display:flex; 
                                 flex-direction:column;    
                                 align-items:center;
                                 display: flex;
                                 align-items: center;
                                 justify-content: center;


    background: rgb(15, 15, 15);">

        <div class="categories-list" style="width: 880px;
                                            display: flex;
                                            flex-direction: row;
                                            flex-wrap: wrap;
                                            justify-content: space-evenly;

                                            margin-top: 20px;
                                            padding: 10px;
                                            border-radius: 15px;

                                            background-color: var(--dark);
                                            font-family: 'Mohave';
                                            text-transform: uppercase;">

            <a href="http://localhost/dashboard/TPE-WEB2/menu" ><- </a>
            
            <p style=""> <?php echo $category->name ?> </p>
        </div>

        <div class="products" style="width: 880px;
                                    display: flex;
                                    flex-direction: row;
                                    flex-wrap: wrap;
                                    justify-content: space-between;
                                    row-gap: 30px;
                                    margin: 20px 0vw 45px 0vw;">

            <?php foreach ($products as $product) : ?>

                <div class="card" style="display: flex;
                                         flex-direction: column;
                                         align-items: center;

                                         width: 200px;
                                         height: 300px;

                                         border-radius: 15px;
                                         border: 1px solid white;

                                         background-color: white;

                                         font-family: 'PT Sans';
                                         font-size: 11px;

                                         box-shadow: 0px 0px 12px 0px rgba(0,0,0,0.78);
                                         -webkit-box-shadow: 0px 0px 12px 0px rgba(0,0,0,0.78);
                                         -moz-box-shadow: 0px 0px 12px 0px rgba(0,0,0,0.78);">

                    <img src=" <?php echo $product->picture ?>" alt="" style="height: 100%;
                                                                              width: 100%;
                                                                              max-width: 100%;
                                                                              max-height: 55%;
                                                                              border-radius: 15px 15px 0px 0px;
                                                                              object-fit: cover;">
                    <div class="price">
                        <p><?php echo $product->price ?></p>
                    </div>

                    <div class="card-info" style="display: flex;
                                                  flex-direction: column;

                                                  height: 50%;
                                                  width: 90%;">
                        <h1 style=""><?php echo $product->name ?></h1>
                        <p style=""><?php echo $product->description ?></p>

                    </div>
                    <button style="background-color: orange;
                                    padding: 5px 0px;
                                    border-radius: 7px;
                                    border: 2px solid rgb(255, 149, 0);
                                    width: 90%;
                                    margin-bottom: 10px;
                                    color:var(--dark);
                                    font-family: 'Ubuntu';
                                    font-weight: bold;
                                    letter-spacing: 0.5px;">Comprar</button>
                </div>

            <?php endforeach ?>

        </div>
    </section>

</body>

</html>