<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="shortcut icon" href="./src/burguer.png">
    <link rel="stylesheet" href="src/style.css">
    <title>Bamba's Burguer</title>
</head>

<body>

    <section style="display: flex;flex-direction:column;align-items:start;padding: 5%">

        <div style="display: flex;flex-direction:row;gap:40px">
            <div style="display:flex;flex-direction:column">
                <img src="<?php echo $product->picture ?>" alt="" style="border-radius:10px;width:400px;height:400px">
            </div>
            <div style="border-left:1px solid gray;padding:40px;width:400px">
                <h1 style="font-family:'Ubuntu';color:white;font-size:35px"><?php echo $product->name ?></h1>
                <h2 style="font-family:'Ubuntu' ;color:white;">$<?php echo $product->price ?></h2>
                <p style="font-family:'Ubuntu';color:white;"><?php echo $product->description ?></p>
                <button>Comprar</button>
            </div>
        </div>

        <div class="addform" style="width:80vw;display:flex;flex-direction:column;">
            <h1 style="text-align: left;width: 80%;color:white;font-family:'Mohave';font-style:italic;font-size:35px;">Editar un producto</h1>
            <form action="" class="" style="display: flex;flex-direction:column;gap:20px;width:400px;">
                <input type="text" placeholder="Nombre del Producto" style="padding: 10px;background-color:white;border:1px solid white;border-radius:5px">
                <input type="text" placeholder="Categoria" style="padding: 10px;background-color:white;border:1px solid white;border-radius:5px">
                <select name="" id="" style="padding: 10px;background-color:white;border:1px solid white;border-radius:5px">
                    <option value="1">Hamburguesa</option>
                    <option value="2">Vegetariano</option>
                    <option value="3">Combo</option>
                    <option value="4">Bebida</option>
                    <option value="5">Papas</option>
                    <option value="6">Postre</option>
                </select>
                <input type="text" placeholder="Precio" style="padding: 10px;background-color:white;border:1px solid white;border-radius:5px">
                <input type="textarea" placeholder="Descripcion" style="padding: 10px;background-color:white;border:1px solid white;border-radius:5px">
                <input type="text" placeholder="Fotografia (URL)" style="padding: 10px;background-color:white;border:1px solid white;border-radius:5px">
                <button type="submit" style="background-color: orange; width:140px;padding:15px;border-radius:5px;border:0;"> Confirmar Edicion</button>
            </form>
        </div>

    </section>


</body>

</html>