<footer>

    <div>
        <img class="footer-pic" src="./src/hamburguer-mono.png" alt="">
        <a href="">Contacto</a>
        <a href="">Sobre Nosotros</a>
    </div>

    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d940.4028681188734!2d-60.801849487158904!3d-37.55210445965899!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9593637fd5fd5607%3A0xa884dce73ad4ec0d!2sLaprida%2C%20Provincia%20de%20Buenos%20Aires!5e0!3m2!1ses-419!2sar!4v1697468242886!5m2!1ses-419!2sar" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</footer>


</body>

</html>