<footer>
    <div>
        <img class="footer-pic" src="./src/hamburguer-mono.png" alt="">
        <a href="">Contacto</a>
        <a href="">Sobre Nosotros</a>
    </div>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d790.7786984294964!2d-60.80223531075891!3d-37.552359139749306!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9593637fd5fd5607%3A0xa884dce73ad4ec0d!2sLaprida%2C%20Provincia%20de%20Buenos%20Aires!5e0!3m2!1ses-419!2sar!4v1697129491677!5m2!1ses-419!2sar" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</footer>


</body>

</html>