<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="./src/burguer.png">
    <link rel="stylesheet" href="src/main.css">
    <title>Bamba's Burguer</title>
</head>

<body>

    <header>
        <div>
            <a href="home"><img src="./src/hamburguer.png" alt="" class="title-pic"></a>
            <p class="title">BAMBA'S</p>

            <a href="http://localhost/dashboard/WEB2/TPE-WEB2/menu">Menu </a>
            <a href="http://localhost/dashboard/WEB2/TPE-WEB2/about">Acerca de nosotros</a>


        </div>
        <div class="login">
            <a href="http://localhost/dashboard/WEB2/TPE-WEB2/login">INICIAR SESION</a>
            <a type="button" href="register" class="btn btn-info">Registrarse</a>

            <?php if (isset($_SESSION['USER_ID']) && ($_SESSION['LOGGED'] == true) && ($_SESSION['USER_EMAIL'] == 'webadmin')) : ?>

                <a type="button" href="http://localhost/dashboard/WEB2/TPE-WEB2/logout">CERRAR SESION </a>
            <?php endif ?>
        </div>
    </header>