<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<? echo BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="./src/burguer.png">
    <link rel="stylesheet" href="src/style.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <title>Bamba's Burguer</title>
</head>

<body>

    <header>
        <div>
            <img src="./src/hamburguer.png" alt="" class="title-pic">
            <p class="title">BAMBA'S</p>
        </div>
        <div>
            <a href="http://localhost/dashboard/TPE-WEB2/menu">Menu</a>
            <a href="http://localhost/dashboard/TPE-WEB2/nosotros">Nosotros</a>
        </div>

        <div class="login">
            <a href="http://localhost/dashboard/TPE-WEB2/login">INICIAR SESION</a>
        </div>
    
    </header>