<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<? echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="./src/burguer.png">
    <link rel="stylesheet" href="/src/style.css">
    <title>Bamba's Burguer</title>
</head>

<body>
    
    <header>
        <a href=""> <img src="./src/hamburguer.png" alt=""> BAMBA'S BURGUERS</a>
        <a href="">Menu</a>
        <a href="">Acerca de nosotros</a>
        <div class="login">
            <button>Iniciar Sesion</button>
        </div>
    </header>
