<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<? echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="./src/burguer.png">
    <link rel="stylesheet" href="src/style.css">
    <title>Bamba's Burguer</title>
</head>
<body>
    <div class="login-bg">
        <div class="login-container">
            <img src="src/hamburguer-mono.png" alt="">
            <input type="text" placeholder="Usuario o Email">
            <input type="password" placeholder="Contraseña">
            <div class="login-buttons">
                <button class="close-login">Atras</button>
                <button class="continue-login">Ingresar</button>
            </div>
        </div>
    </div>
</body>
</html>